name: "CLA assistant lite"
description: "An action to handle the Contributor License Agreement"
author: "SAP"
branding:
  icon: "award"
  color: blue
inputs:
  path-to-signatures:
    description: "Give a path for storing CLAs in a json file "
    default: "./signatures/cla.json"
  branch:
    description: "select a branch where all the CLAs are stored"
    default: "master"
  blockchain-storage-flag:
    description: "Optional functionality to store all the blockchain signatures in the ethirium blockchain as a smart contract"
    default: false
  empty-commit-flag:
    description: "GitHub Actions will add empty commit whenever the user signs the CLA (optional)"
    default: true
  allowlist:
    description: "users in the allow list don't have to sign the CLA document"
  path-to-cla-document:
    description: "Fully qualified web link to cla document Example: https://github.com/cla-assistant/github-action/blob/master/SAPCLA.md"
  persistance-repository:
    description: "Give name of the repository in the same organization to store signatures document in"

runs:
  using: "node12"
  main: "lib/main.js"
